//
// Autogenerated by Thrift Compiler (0.16.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare enum CodeChatClientLocation {
  url = 0,
  html = 1,
  browser = 2,
}

declare class RenderClientReturn {
  public html: string;
  public id: number;
  public error: string;

    constructor(args?: { html: string; id: number; error: string; });
}

declare var THRIFT_PORT: number;
