# `book.toml`
# ===========
# This files provides basic project setup for an mdbook. It also contains the necessary setup to run CodeChat.
#
# Book configuration
# ------------------
[book]
authors = ["bjones1"]
language = "en"
multilingual = false
src = "src"
title = "mdbook template"

# CodeChat
# --------
# This is required in order to run CodeChat on mdbook files.
[preprocessor.CodeChat]
# This is only necessary if you want the [mdbook include](https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html) directive to run before CodeChat. It's used here as a hack to include this file, since files outside the `src/` directory can't normally be added to the book.
after = [ "links" ]

# Optional: `lexer_for_glob` is a dict of ``{glob_: str, lexer_alias: str}``,
# which uses ``lexer_alias`` (e.g. a lexer's
# [short name](http://pygments.org/docs/lexers/)) to analyze any file which
# matches the given glob-style pattern (e.g.
# [glob](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.match)).
[preprocessor.CodeChat.lexer_for_glob]
# Some (commented-out) examples:
#"*.js" = "JavaScript"
#"*.css" = "CSS"