//
// Autogenerated by Thrift Compiler (0.13.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');


declare enum CodeChatClientLocation {
  url = 0,
  html = 1,
  browser = 2,
}

declare enum GetResultType {
  html = 0,
  build = 1,
  errors = 2,
  command = 3,
}

declare class RenderClientReturn {
  public html: string;
  public id: number;
  public error: string;

    constructor(args?: { html: string; id: number; error: string; });
}

declare class GetResultReturn {
  public get_result_type: GetResultType;
  public text: string;

    constructor(args?: { get_result_type: GetResultType; text: string; });
}
